"""changed product table

Revision ID: 49316a9a0a22
Revises: c902f0d2e1cd
Create Date: 2024-02-08 18:37:36.755556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49316a9a0a22'
down_revision = 'c902f0d2e1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muscle', sa.String(length=200), nullable=True))
        batch_op.drop_column('exercise')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('muscle')

    # ### end Alembic commands ###
