"""change sets back to numeric

Revision ID: 5678471ac98f
Revises: fa2ac66c9694
Create Date: 2024-02-08 19:27:53.971826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5678471ac98f'
down_revision = 'fa2ac66c9694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prod_order', schema=None) as batch_op:
        batch_op.alter_column('sets',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('sets',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('sets',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('prod_order', schema=None) as batch_op:
        batch_op.alter_column('sets',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
